# day 15

I learned that local storage doesnt throw an error when it can not find a key, instead the storeage will just happely give back a Null object. Null in JS are objects which are truthie.
This is very unfortunate because it means that we can no check for Null and undefined at the same time because undefined is falsie. In TypeScript this is an optiont to get rid of any occurences of Null but we still have undefiend to deal with because there are some things that are trutly undefined.

I also learned that throwing my own error is probably not the best thing to do if I am also using try in those fucntions. The mean reason is that it is hard to reason about the code because as soon as a function throws inside a try then it imiidly goes into the catch block with out running the other code in the try block. This can be confusing becase we could be reacting to our own thrown errors even thought the API we are using the try for does not trow any error.

I did find try to be very usefyll when I am trying to see is an object contains a certain propety, this allowed me to do some kind of poplymorphism because I was able to treat a objects the same way an a plain object.  

try {
  classObject['someClassMethod']();
} else {
  plainObject['somePlainObjectMethod']();
}
